# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31b47df93ce404cc138ca4c63f5ead3aef380d00c88bb87c82367e24143159878e41ba5dab552940c2f653b41013e846624f19f5c138a67002ed4b62e12cf6d3

test:
  secret_key_base: 25e79b417ce8f9c655337dc2150f75014ea04d1b2b489cf373a4f0e465926aa6a8f0d110b4aedadb53f982464c824a6044fd3eedd7815d8add676048d5d880eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
